# Generated by Django 4.1.7 on 2023-03-15 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_podik_param'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podik',
            options={'verbose_name': 'Солоденький пісюнчик', 'verbose_name_plural': 'Солоденькі пісюнчики'},
        ),
    ]
