# Generated by Django 4.1.7 on 2023-03-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_podik_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podik',
            options={'ordering': ['categoryId', 'name'], 'verbose_name': 'Солоденький пісюнчик', 'verbose_name_plural': 'Солоденькі пісюнчики'},
        ),
        migrations.AlterField(
            model_name='podik',
            name='available',
            field=models.BooleanField(verbose_name='Доступність'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='categoryId',
            field=models.IntegerField(verbose_name='Id категорії'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='currencyId',
            field=models.CharField(max_length=255, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва продукту'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='picture',
            field=models.CharField(max_length=255, verbose_name='URL картинки'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='quantity_in_stock',
            field=models.IntegerField(verbose_name='Кількість товару склад'),
        ),
    ]
