# Generated by Django 4.1.7 on 2023-03-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_podik_options_alter_podik_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podik',
            name='description',
        ),
    ]
