# Generated by Django 4.1.7 on 2023-03-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_podik_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podik',
            options={'ordering': ['categoryId', 'name'], 'verbose_name': 'Електронна цигарка', 'verbose_name_plural': 'Електронні цигарки'},
        ),
        migrations.AddField(
            model_name='podik',
            name='param',
            field=models.TextField(null=True),
        ),
    ]
