# Generated by Django 4.1.7 on 2023-03-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_podik_options_podik_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='podik',
            name='atomizer_volume',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podik',
            name='battery_capacity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podik',
            name='cartridge_capacity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podik',
            name='compatibility_selection',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podik',
            name='flavour',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podik',
            name='fluid_volume',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podik',
            name='max_power',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podik',
            name='nicotine_strength',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podik',
            name='nicotine_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podik',
            name='power',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podik',
            name='puffs_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podik',
            name='rechargeable',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='podik',
            name='resistance',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
