# Generated by Django 4.1.7 on 2023-03-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_podik_atomizer_volume_podik_battery_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podik',
            name='nicotine_type',
        ),
    ]
