# Generated by Django 4.1.7 on 2023-03-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_podik_nicotine_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPost',
            fields=[
                ('city', models.CharField(max_length=255)),
                ('ref', models.CharField(max_length=37, primary_key=True, serialize=False)),
                ('warehouses', models.TextField()),
                ('area', models.CharField(max_length=255)),
                ('isAreaCenter', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='podik',
            name='atomizer_volume',
            field=models.CharField(max_length=255, null=True, verbose_name='Объем атомайзера'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='battery_capacity',
            field=models.CharField(max_length=255, null=True, verbose_name='Ёмкость аккумулятора'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='cartridge_capacity',
            field=models.CharField(max_length=255, null=True, verbose_name='Объём картриджа'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='compatibility_selection',
            field=models.CharField(max_length=255, null=True, verbose_name='Выбор совместимости'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='flavour',
            field=models.CharField(max_length=255, null=True, verbose_name='Выбор вкуса'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='fluid_volume',
            field=models.CharField(max_length=255, null=True, verbose_name='Объем жидкости'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='max_power',
            field=models.CharField(max_length=255, null=True, verbose_name='Максимальная мощность'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='nicotine_strength',
            field=models.CharField(max_length=255, null=True, verbose_name='Крепость никотина'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='power',
            field=models.CharField(max_length=255, null=True, verbose_name='Мощность'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='puffs_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Количество затяжек'),
        ),
        migrations.AlterField(
            model_name='podik',
            name='rechargeable',
            field=models.BooleanField(null=True, verbose_name="Перезаряжаемые'"),
        ),
        migrations.AlterField(
            model_name='podik',
            name='resistance',
            field=models.CharField(max_length=255, null=True, verbose_name='Выбор сопротивления'),
        ),
    ]
